// Generated by nuxi
/// <reference types="@nuxt/image-edge" />
/// <reference types="@nuxtjs/i18n" />
/// <reference types="@nuxtjs/tailwindcss" />
/// <reference types="@vueuse/nuxt" />
/// <reference types="@nuxt/telemetry" />
/// <reference types="nuxt" />
/// <reference path="types/plugins.d.ts" />
/// <reference path="types/vue-shim.d.ts" />
/// <reference path="types/schema.d.ts" />
/// <reference path="types/app.config.d.ts" />
/// <reference path="../node_modules/@nuxtjs/i18n/dist/runtime/types" />
/// <reference types="vue-router" />
/// <reference path="types/middleware.d.ts" />
/// <reference path="types/layouts.d.ts" />
/// <reference path="components.d.ts" />
/// <reference path="types/imports.d.ts" />
/// <reference path="imports.d.ts" />
/// <reference path="types/nitro.d.ts" />

export {}
